

top_genres = ["RPG", "Adventure", "Action", "Casual", "Strategy", "Simulation", "Sports", "Racing", "Sandbox",
              "Visual Novel", "Puzzle", "Platformer", "Shooter", "Roguelike"]

sub_genres = ["JRPG", "Strategy RPG", "Party-Based RPG", "Action RPG", "MMORPG", "Tactical RPG", "CRPG", "Souls-like",
              "Turn-Based Strategy", "RTS", "Grand Strategy", "Action RTS", "City Builder", "Turn-Based Tactics",
              "Real Time Tactics", "Tower Defense", "Action-Adventure", "Action Roguelike", "Roguelite", "Traditional Roguelike",
              "Dungeon Crawler", "Hack and Slash", "Roguevania", "Metroidvania", "MOBA", "Battle Royale", "Precision Platformer",
              "3D Platformer", "Puzzle Platformer", "2D Platformer",
              "Arcade", "FPS", "Arena Shooter", "Looter Shooter", "Hero Shooter", "Third-Person Shooter",
              "Top-Down Shooter","Twin Stick Shooter", "Boomer Shooter", "On-Rails Shooter", "Spectacle fighter",
              "3D Fighter", "2D Fighter", "Bullet Hell", "Shoot Em Up", "Beat em up", "Immersive Sim", "Life Sim",
              "Dating Sim", "Political Sim", "Automobile Sim", "Colony Sim", "Space Sim", "Medical Sim", "Farming Sim",
              "Walking Simulator", "Outbreak Sim", "Clicker", "Idler", "Match 3", "Sokoban", "Solitaire", "Spelling",
              "Typing", "Word Game", "Education", "Trivia", "Board Game", "Tabletop", "Point & Click", "Hidden Object",
              "Collectathon", "Card Game", "Trading Card Game", "Card Battler", "Auto Battler", "Side Scroller",
              "Runner", "Interactive Fiction", "Choose Your Own Adventure", "Free to Play"]
vis_tags = ["2D", "3D", "Pixel Graphics", "Anime", "Cute", "Colorful", "Top-Down", "Third Person", "First-Person",
                 "Stylized", "Cartoony", "Realistic", "Hand-drawn", "Isometric", "Cartoon", "Text-Based", "2.5D",
                 "Minimalist", "Cinematic", "VR", "Comic Book", "Psychedelic", "Abstract", "Noir", "3D Vision",
                 "Voxel", "FMV", "HDR Supported", "Split Screen", "Beautiful", "360 Video"]
theme_tags = ["Fantasy", "Dark Fantasy", "Magic", "Medieval",
              "Horror", "Survival Horror", "Psychological Horror",
              "Dark", "Surreal", "Atmospheric", "Mystery", "Thriller", "Drama", "Romance",
              "Funny", "Parody", "Comedy", "Dark Comedy", "Dark Humor", "Satire",
              "Retro", "Sci-fi", "Futuristic", "Steampunk", "Gothic", "Lovecraftian",
              "Cold War", "Historical", "1990s", "1980s", "Modern", "Mars",
              "Survival", "Crafting",
              "Tactical", "Relaxing", "Family Friendly", "Lore-Rich",
              "Old School", "Post-apocalyptic", "Building", "Management", "Emotional", "Loot",
              "Zombies", "Space", "Demons", "LGBTQ+",
              "Nature", "Cyberpunk", "War",
              "Mythology", "Stealth", "Swordplay", "Dragons", "Detective", "Investigation", "Alternate History",
              "Logic", "Supernatural", "Economy", "Robots", "Aliens", "Military", "Naval", "Memes",
              "Artificial Intelligence", "Psychological", "Cooking",
              "Fishing", "Crime", "Vampire", "Agriculture", "Underground", "Cats", "Philosophical",
              "Martial Arts", "Mining", "Pirates", "Capitalism", "Politics", "Automation", "Mechs", "Conspiracy",
              "Hunting", "Destruction", "Driving", "Time Travel", "Political", "Archery", "Faith", "Assassin",
              "America", "Ninja", "Diplomacy", "Sailing", "Superhero", "Science", "Western", "Parkour",
              "Dog", "Otome", "Hacking", "Dinosaurs", "Werewolves", "Transhumanism", "World War II",
              "Underwater", "Gambling", "Heist", "Foreign", "Rome", "Horses", "Illuminati", "Tanks", "Game Development",
              "Programming", "Snow", "Boxing", "Sniper", "Trains", "Football (Soccer)",
              "Transportation", "World War I", "Warhammer 40K", "Submarine", "LEGO", "Wrestling", "Offroad",
              "Basketball", "Golf", "Bikes", "Motorbike", "Skateboarding", "Jet", "Football (American)", "Tennis",
              "Cycling", "Baseball", "Hockey", "Bowling", "Mini Golf", "Skating", "BMX", "Pool", "Motocross", "Skiing",
              "Lemmings", "Snowboarding", "ATV", "Dystopian", "Vikings"]
feature_tags = ["Open World", "Combat", "Turn-Based Combat", "Naval Combat", "Vehicular Combat", "PvE", "PvP",
                "Female Protagonist", "Linear", "Nonlinear", "Multiple Endings", "Choices Matter",
                "Story Rich", "Narrative",  "Narration", "Dynamic Narration", "Conversation",
                     "Character Customization", "Controller", "Procedural Generation",
                     "Base Building", "Perma Death", "Resource Management", "Deckbuilding",
                     "Inventory Management", "Class-Based", "Grid-Based Movement", "Hex Grid",
                    "Physics", "Team-Based", "Trading", "Score Attack", "Gun Customization", "Tutorial",
                     "Moddable", "Quick-Time Events", "Level Editor",
                     "Time Manipulation", "Bullet Time", "6DOF",
                     "Music-Based Procedural Generation", "Asymmetric VR"]
play_tags = ["Singleplayer", "Multiplayer", "Co-op", "Online Co-Op", "Massively Multiplayer", "Local Co-Op",
                  "Local Multiplayer", "Co-op Campaign", "4 Player Local", "Asynchronous Multiplayer"]